import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    paddingTop: 30,
    paddingBottom: 25,
    paddingHorizontal: 25,
    fontFamily: "Helvetica",
  },
  header: {
    position: "absolute",
    top: 20,
    left: 25,
    right: 25,
    fontSize: 11,
    color: "#0f172a",
    borderBottom: "1pt solid #0ea5e9",
    paddingBottom: 6,
    textAlign: "center",
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 25,
    right: 25,
    textAlign: "center",
    fontSize: 9,
    color: "#64748b",
    borderTop: "1pt solid #0ea5e9",
    paddingTop: 6,
    fontStyle: "italic",
  },
  section: {
    marginBottom: 8,
    padding: 8,
    backgroundColor: "#f8fafc",
    borderRadius: 6,
    borderLeft: "2pt solid #0ea5e9",
  },
  title: {
    fontSize: 20,
    color: "#0ea5e9",
    marginBottom: 8,
    fontWeight: "bold",
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 13,
    marginBottom: 6,
    fontWeight: "bold",
    color: "#1e293b",
    borderBottom: "0.5pt solid #e2e8f0",
    paddingBottom: 3,
  },
  text: {
    fontSize: 10,
    color: "#334155",
    lineHeight: 1.3,
    marginBottom: 2,
  },
  listItem: {
    fontSize: 10,
    marginLeft: 10,
    marginBottom: 2,
    color: "#475569",
    lineHeight: 1.3,
  },
});
