// Curriculum.styles.ts
import { StyleSheet } from "@react-pdf/renderer";

export const styles = StyleSheet.create({
  page: {
    flexDirection: "column",
    backgroundColor: "#ffffff",
    paddingTop: 60,
    paddingBottom: 40,
    paddingHorizontal: 40,
    fontFamily: "Helvetica",
  },
  header: {
    position: "absolute",
    top: 20,
    left: 40,
    right: 40,
    fontSize: 11,
    color: "#0f172a",
    borderBottom: "1pt solid #0ea5e9",
    paddingBottom: 6,
    textAlign: "center",
    fontWeight: "bold",
    letterSpacing: 0.5,
  },
  footer: {
    position: "absolute",
    bottom: 20,
    left: 40,
    right: 40,
    textAlign: "center",
    fontSize: 9,
    color: "#64748b",
    borderTop: "1pt solid #0ea5e9",
    paddingTop: 6,
    fontStyle: "italic",
  },
  section: {
    marginBottom: 18,
    padding: 12,
    backgroundColor: "#f8fafc",
    borderRadius: 6,
    borderLeft: "3pt solid #0ea5e9",
  },
  title: {
    fontSize: 22,
    color: "#0ea5e9",
    marginBottom: 10,
    fontWeight: "bold",
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  subtitle: {
    fontSize: 15,
    marginBottom: 8,
    fontWeight: "bold",
    color: "#1e293b",
    borderBottom: "0.5pt solid #e2e8f0",
    paddingBottom: 4,
  },
  text: {
    fontSize: 12,
    color: "#334155",
    lineHeight: 1.5,
    marginBottom: 4,
  },
  listItem: {
    fontSize: 12,
    marginLeft: 14,
    marginBottom: 3,
    color: "#475569",
    lineHeight: 1.4,
  },
});
